name: Lint
on: [push]
jobs:
  mypy:
    name: Python Type Check
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9.16
          architecture: x64
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install mypy
        run: pip install mypy
      - name: ls
        run: echo ${{ github.repository }} && pwd && ls && ls ${{ github.repository }}
      - name: Run mypy
        run: mypy -p ${{ github.repository }}/frontend
        # with:
        #   path: './frontend'
