name: Python unit tests

on: [push]

jobs:
  build:

    runs-on: self-hosted
    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
      - uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.SSHKEY }}
      - name: install the package
        run: |
          source ~/venv/frontend-env/bin/activate
          pip install --force-reinstall .
          cd scripts && BUILD_DIR=~/frontend ./compile_longobj.sh && cd ..
      - name: install dependency
        run: |
          source /opt/spack/share/spack/setup-env.sh
          spack load cuda@11.8.0 /jb4mlxg
          spack load python@3.9.12%gcc@=11.3.0
          source ~/venv/frontend-env/bin/activate
          pip install --upgrade -r requirements.txt -f https://download.pytorch.org/whl/torch_stable.html
          if ! pip show transformers &> /dev/null; then
            pip install transformers==v4.29.1
          fi
      - name: Test with pytest
        run: |
          source /opt/spack/share/spack/setup-env.sh
          spack load cuda@11.8.0 /jb4mlxg
          spack load python@3.9.12%gcc@=11.3.0
          source ~/venv/frontend-env/bin/activate
          srun --gres=gpu:v100:1 --exclusive ./scripts/pytest_with_preload.sh -vs test
