name: Python unit tests

on: [push]

jobs:
  build:

    runs-on: self-hosted
    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
      - uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.SSHKEY }}
      - name: install the package
        run: |
          source ~/venv/frontend-env/bin/activate
          pip install --force-reinstall .
      - name: Test with pytest
        run: |
          source ~/venv/frontend-env/bin/activate
          pytest -v test