name: Python unit tests

on: [push]

jobs:
  build:

    runs-on: self-hosted
    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
      - uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.SSHKEY }}
      - name: install the package
        run: |
          source ~/venv/frontend-env/bin/activate
          pip install --force-reinstall .
      - name: Test with pytest
        run: |
          source /opt/spack/share/spack/setup-env.sh
          spack load cuda@11.8.0 /jb4mlxg
          source ~/venv/frontend-env/bin/activate
          pip install --upgrade -r requirements.txt -f https://download.pytorch.org/whl/torch_stable.html
          pytest -vs test